### ISSUE TITLE
Mac OSX 10.10.5

### ISSUE THREAD

**Issue by Spartan5685** [z1lc/AutoDefine#6]
Keep getting this error every time I press "Cmd+E"
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/Users/Spartan5685/Documents/Anki/addons/AutoDefineAddon/core.py", line 175, in <lambda>
    editor._addButton("AutoDefine", lambda ed=editor: get_definition(ed),
  File "/Users/Spartan5685/Documents/Anki/addons/AutoDefineAddon/core.py", line 57, in get_definition
    etree = ET.parse(urllib.urlopen(url))
  File "xml/etree/ElementTree.pyc", line 1182, in parse
  File "xml/etree/ElementTree.pyc", line 656, in parse
  File "xml/etree/ElementTree.pyc", line 1642, in feed
  File "xml/etree/ElementTree.pyc", line 1506, in _raiseerror
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by mazei** [comment]
I got the same error.

**Comment by z1lc** [comment]
I'm unable to reproduce this error, even on Mac. Could either of you (@Spartan5685 @mazei) post the specific word you're using?

**Comment by z1lc** [comment]
Closing due to inactivity.
